# -*- coding: utf-8 -*-
"""
Created on Sun Mar  5 19:18:46 2017
@author: Cesar Alvarez
Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
22=4, 23=8, 24=16, 25=32
32=9, 33=27, 34=81, 35=243
42=16, 43=64, 44=256, 45=1024
52=25, 53=125, 54=625, 55=3125
If they are then placed in numerical order, with any repeats removed, we get 
the following sequence of 15 distinct terms:
4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and
 2 ≤ b ≤ 100?
"""


    

N=int(input())
import math

#test=10000
#N=test

#LogTerms={round(b*math.log10(a),9) for a in range(2,test+1) for b in range(2,test+1)}
#print(len(LogTerms))


DistinctTermsSet=set()
abset=set()
for a in range(2,test+1):
    for b in range(2,test+1):
        if (b/2 - int(b/2)) == 0 and (b/2 >= 2):
            abset.add((a**2,b/2))
#            try:
#                abset.remove((a,b))
#            except:
#                pass
        if ((a,b) in abset) == False:
                DistinctTermsSet.add(round(b*math.log10(a),9))
        
print(len(DistinctTermsSet))

#DistinctTermsSet={a**b:(a,b) for a in range(2,test+1) for b in range(2,test+1)}
#print(len(DistinctTermsSet))
